apiVersion: apps/v1
kind: Deployment
metadata:
        name: authentication-service
        labels:
                app: authentication-service 
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: authentication-service
        template:
                metadata:
                        labels:
                                app: authentication-service
                spec:
                        containers:
                                - image: docker.io/wrusselly/authentication-service
                                  name: authentication-service
                                  ports:
                                          - containerPort: 3000
                                  env:
                                          - name: ACTIVATION_LINK
                                            value: http://34.90.184.123/authentication/api/activate        
